baseURL = "https://labinitio.org/" 
languageCode = 'en-us'
title = 'Lab Initio'
theme = 'netlify-basic'

[params]
  math = true

# ===========================================================================
# Main Navigation Menu (using theme-compatible syntax)
# ===========================================================================

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 20

[[menu.main]]
  name = "AI"
  url = "/platform/"
  weight = 25 # Adjusted weight to place it after Publications
  identifier = "platform"

[[menu.main]]
  name = "AI Breakthrough"
  url = "/platform/ai-breakthrough/"
  weight = 10
  parent = "platform"

[[menu.main]]
  name = "The Discovery Engine"
  url = "/platform/discovery-engine/"
  weight = 20
  parent = "platform"

[[menu.main]]
  name = "Solutions & Case Studies"
  url = "/platform/solutions/"
  weight = 30
  parent = "platform"

[[menu.main]]
  name = "Partner With Us"
  url = "/platform/partner-with-us/"
  weight = 40
  parent = "platform"

[[menu.main]]
  name = "Awards"
  url = "/awards/"
  weight = 30

[[menu.main]]
  name = "Profile"
  url = "/academic_profile/"
  weight = 40

[[menu.main]]
  name = "Editor"
  url = "/editor/"
  weight = 50

[[menu.main]]
  name = "Explore"
  url = "/explore/"
  weight = 60

[[menu.main]]
  name = "XYZ"
  url = "/xyzview/"
  weight = 70

[[menu.main]]
  name = "Join"
  url = "/join/"
  weight = 80

[[menu.main]]
  name = "Bulletin"
  url = "/bulletin/"
  weight = 85

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 90

# ===========================================================================
# Markup Settings
# ===========================================================================

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
