baseURL = "https://aatacc.org/" 
languageCode = 'en-us'
title = 'AATACC'
theme = 'netlify-basic'

[params]
  math = true

# ===========================================================================
# Main Navigation Menu (using theme-compatible syntax)
# ===========================================================================

[[menu.main]]
# ===========================================================================
# AATACC Main Navigation Menu
# ===========================================================================

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 20
  identifier = "about"

[[menu.main]]
  name = "Mission"
  url = "/about/mission/"
  parent = "about"
  weight = 10

[[menu.main]]
  name = "Board"
  url = "/about/board/"
  parent = "about"
  weight = 20

[[menu.main]]
  name = "Awards"
  url = "/awards/"
  weight = 30
  hasChildren = true
  [[menu.main.children]]
    name = "Distinguished Lecturers"
    url = "/awards-funding/distinguished-lecturers/"
    weight = 1
  [[menu.main.children]]
    name = "International Fellows"
    url = "/awards-funding/international-fellows/"
    weight = 2

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 100

# ===========================================================================
# Markup Settings
# ===========================================================================

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
