baseURL = "https://aatacc.org/" 
languageCode = 'en-us'
title = 'AATACC'
theme = 'netlify-basic'

[params]
  math = true

# ===========================================================================
# AATACC Main Navigation Menu
# ===========================================================================

[[menu.main]]
  name = "About"
  url = "/about/mission/" # <-- Directs the top-level link to the mission page
  weight = 20
  identifier = "about"

[[menu.main]]
  name = "Board"
  url = "/about/board/"
  parent = "about"
  weight = 20

[[menu.main]]
  name = "Awards"
  url = "/awards/"
  weight = 30
  identifier = "awards" # <-- FIX: Added identifier for consistency

[[menu.main]]
  name = "Distinguished Lecturers"
  url = "/awards/distinguished-lecturers/" # <-- FIX: Corrected URL path
  parent = "awards"
  weight = 1

[[menu.main]]
  name = "International Fellows"
  url = "/awards/international-fellows/" # <-- FIX: Corrected URL path
  parent = "awards"
  weight = 2

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 100

# ===========================================================================
# Markup Settings
# ===========================================================================

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
